version: '3.3'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=pylon
    deploy:
       placement:
         constraints:
           - node.labels.type == primary
           - node.role == worker

volumes:
  mongodb-data:
    driver: local
