version: '3.3'
services:
  pylon-api:
    image: pylon-api:sandbox
    ports:
      - 3001:3000
    volumes:
      - pylon-api-log:/opt/app/logs
    environment:
      - NODE_ENV=sandbox
    deploy:
       placement:
         constraints:
           - node.role == worker
volumes:
  pylon-api-log:
    driver: local
